clear;
clc;

projectRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(projectRoot));

cfg = defaultPackConfig();
modelName = cfg.sim.modelName;

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

if exist(modelName + ".slx", "file")
    delete(modelName + ".slx");
end

new_system(modelName);
open_system(modelName);
set_param(modelName, "Solver", "FixedStepAuto", "StopTime", num2str(cfg.sim.duration_s));

add_block("simulink/Sources/Repeating Sequence Stair", modelName + "/CurrentProfile", ...
    "Position", [30 130 130 190], ...
    "OutValues", "[0 18 35 62 80 52 95 70 120 48]", ...
    "TimeValues", "[0 40 160 280 430 610 760 900 1040 1120]");
add_block("simulink/Discontinuities/Saturation", modelName + "/DischargeOnly", ...
    "Position", [170 130 230 190], ...
    "UpperLimit", "inf", ...
    "LowerLimit", "0");
add_block("simulink/Sources/Constant", modelName + "/AmbientTemp", ...
    "Position", [30 240 130 270], ...
    "Value", num2str(cfg.thermal.ambientTempC));

add_block("simulink/User-Defined Functions/MATLAB Function", modelName + "/CellModel", ...
    "Position", [300 60 560 280]);
add_block("simulink/User-Defined Functions/MATLAB Function", modelName + "/BatterySupervisor", ...
    "Position", [650 40 980 290]);
add_block("simulink/User-Defined Functions/MATLAB Function", modelName + "/ThermalManager", ...
    "Position", [650 330 980 500]);
add_block("simulink/User-Defined Functions/MATLAB Function", modelName + "/EnergyEstimator", ...
    "Position", [650 540 980 700]);
add_block("simulink/User-Defined Functions/MATLAB Function", modelName + "/HealthMonitor", ...
    "Position", [1020 40 1320 250]);
add_block("simulink/User-Defined Functions/MATLAB Function", modelName + "/CommEncoder", ...
    "Position", [1020 300 1320 520]);

cellCode = sprintf([ ...
    'function [terminalVoltage, cellTempC, ocv, soc, r0, lossPowerW, coreTempC, surfaceTempC] = f(dischargeCurrent, ambientTempC)\n' ...
    'persistent socState coreTemp surfaceTemp\n' ...
    'if isempty(socState)\n' ...
    '    socState = 0.85;\n' ...
    '    coreTemp = 20;\n' ...
    '    surfaceTemp = 20;\n' ...
    'end\n' ...
    'dt = 1.0;\n' ...
    'capacityAs = 31 * 3600;\n' ...
    'r0 = 0.0045 + 0.0015 * (1 - socState);\n' ...
    'socState = min(max(socState - dischargeCurrent * dt / capacityAs, 0.02), 1.0);\n' ...
    'ocv = 2.7 + 1.5 * socState;\n' ...
    'terminalVoltage = ocv - dischargeCurrent * r0;\n' ...
    'lossPowerW = dischargeCurrent^2 * r0;\n' ...
    'coreTemp = coreTemp + dt * ((lossPowerW - (coreTemp - surfaceTemp) / 0.9) / (0.8 * 900));\n' ...
    'surfaceTemp = surfaceTemp + dt * (((coreTemp - surfaceTemp) / 0.9 - (surfaceTemp - ambientTempC) / 3.2) / (0.8 * 900));\n' ...
    'cellTempC = 0.55 * coreTemp + 0.45 * surfaceTemp;\n' ...
    'coreTempC = coreTemp;\n' ...
    'surfaceTempC = surfaceTemp;\n' ...
    'soc = socState;\n' ...
    'end\n']);

supervisorCode = sprintf([ ...
    'function [safeCurrent, trigger, uvFlag, ocFlag, tempFlag, currentLimit, modeCode, derateFlag, severity] = f(voltage, currentIn, tempC, soc, lossPowerW)\n' ...
    'uvFlag = double(voltage <= %.6f);\n' ...
    'ocFlag = double(currentIn >= %.6f);\n' ...
    'tempFlag = double(tempC <= %.6f || tempC >= %.6f);\n' ...
    'tempScale = 1;\n' ...
    'if tempC > 45\n' ...
    '    tempScale = max(0, 1 - (tempC - 45) / (58 - 45));\n' ...
    'end\n' ...
    'socScale = 1;\n' ...
    'if soc < 0.12\n' ...
    '    socScale = max(0, (soc - 0.05) / (0.12 - 0.05));\n' ...
    'end\n' ...
    'voltageScale = 1;\n' ...
    'if voltage < 3.0\n' ...
    '    voltageScale = max(0, (voltage - 2.75) / (3.0 - 2.75));\n' ...
    'end\n' ...
    'powerScale = 1;\n' ...
    'if lossPowerW > 120\n' ...
    '    powerScale = max(0, 1 - (lossPowerW - 120) / 200);\n' ...
    'end\n' ...
    'currentLimit = %.6f * min([tempScale socScale voltageScale powerScale]);\n' ...
    'derateFlag = double(currentLimit < %.6f);\n' ...
    'trigger = double(uvFlag || ocFlag || tempFlag);\n' ...
    'safeCurrent = min(currentIn, currentLimit) * double(trigger == 0);\n' ...
    'modeCode = 0;\n' ...
    'if trigger == 1\n' ...
    '    modeCode = 3;\n' ...
    'elseif derateFlag == 1\n' ...
    '    modeCode = 2;\n' ...
    'elseif currentIn > 1\n' ...
    '    modeCode = 1;\n' ...
    'end\n' ...
    'severity = uvFlag * 3 + ocFlag * 3 + tempFlag * 2;\n' ...
    'severity = min(severity, 3);\n' ...
    'end\n'], ...
    cfg.safety.underVoltageCell, cfg.safety.overCurrentDischargeA, ...
    cfg.safety.underTempC, cfg.safety.overTempC, ...
    cfg.safety.overCurrentDischargeA, cfg.safety.overCurrentDischargeA);

thermalCode = sprintf([ ...
    'function [coolingLevel, thermalScore, hotFlag] = f(cellTempC, coreTempC, surfaceTempC)\n' ...
    'hotFlag = double(cellTempC >= %.6f || coreTempC >= %.6f || surfaceTempC >= %.6f);\n' ...
    'thermalScore = max([cellTempC / %.6f, coreTempC / %.6f, surfaceTempC / %.6f]);\n' ...
    'coolingLevel = min(max((cellTempC - 30) / 20, 0), 1);\n' ...
    'end\n'], cfg.safety.overTempC, cfg.safety.maxCoreTempC, cfg.safety.maxSurfaceTempC, ...
    cfg.safety.overTempC, cfg.safety.maxCoreTempC, cfg.safety.maxSurfaceTempC);

energyCode = sprintf([ ...
    'function [packPowerW, remainingEnergyWh, rangeKm, availablePowerW, sopPowerW] = f(voltage, current, soc, lossPowerW)\n' ...
    'packPowerW = voltage * current;\n' ...
    'remainingEnergyWh = max(0, soc * %.6f);\n' ...
    'rangeKm = remainingEnergyWh / %.6f;\n' ...
    'availablePowerW = max(0, %.6f - lossPowerW);\n' ...
    'sopPowerW = min(availablePowerW, %.6f * soc);\n' ...
    'end\n'], cfg.pack.nominalEnergyWh, cfg.vehicle.whPerKm, cfg.safety.maxPowerW, cfg.supervisor.sopPowerCeilingW);

healthCode = sprintf([ ...
    'function [healthScore, imbalancePenalty, sensorPenalty] = f(voltage, current, tempC, modeCode)\n' ...
    'imbalancePenalty = min(max(abs(voltage - 3.7) / 1.5, 0), 1);\n' ...
    'sensorPenalty = min(max(abs(current) / 300, 0), 1) * 0.2 + min(max(tempC / 100, 0), 1) * 0.1;\n' ...
    'healthScore = max(0, min(1, 1 - 0.35 * imbalancePenalty - sensorPenalty - 0.08 * modeCode));\n' ...
    'end\n']);

commCode = sprintf([ ...
    'function [frameId, voltageRaw, currentRaw, tempRaw, socRaw, healthRaw, severityRaw] = f(voltage, current, tempC, soc, healthScore, severity)\n' ...
    'frameId = %.6f;\n' ...
    'voltageRaw = round(voltage * %.6f);\n' ...
    'currentRaw = round(current * %.6f);\n' ...
    'tempRaw = round(tempC * %.6f);\n' ...
    'socRaw = round(soc * %.6f);\n' ...
    'healthRaw = round(healthScore * 1000);\n' ...
    'severityRaw = round(severity);\n' ...
    'end\n'], cfg.comm.frameBaseId + cfg.comm.nodeId, ...
    cfg.comm.scaling.voltage, cfg.comm.scaling.current, cfg.comm.scaling.temp, cfg.comm.scaling.soc);

set_param(modelName + "/CellModel", "Script", cellCode);
set_param(modelName + "/BatterySupervisor", "Script", supervisorCode);
set_param(modelName + "/ThermalManager", "Script", thermalCode);
set_param(modelName + "/EnergyEstimator", "Script", energyCode);
set_param(modelName + "/HealthMonitor", "Script", healthCode);
set_param(modelName + "/CommEncoder", "Script", commCode);
set_param(modelName, "SimulationCommand", "update");

add_block("simulink/Sinks/Scope", modelName + "/SystemScope", ...
    "Position", [1370 90 1540 560], ...
    "NumInputPorts", "24");

add_line(modelName, "CurrentProfile/1", "DischargeOnly/1", "autorouting", "on");
add_line(modelName, "DischargeOnly/1", "CellModel/1", "autorouting", "on");
add_line(modelName, "AmbientTemp/1", "CellModel/2", "autorouting", "on");

add_line(modelName, "CellModel/1", "BatterySupervisor/1", "autorouting", "on");
add_line(modelName, "DischargeOnly/1", "BatterySupervisor/2", "autorouting", "on");
add_line(modelName, "CellModel/2", "BatterySupervisor/3", "autorouting", "on");
add_line(modelName, "CellModel/4", "BatterySupervisor/4", "autorouting", "on");
add_line(modelName, "CellModel/6", "BatterySupervisor/5", "autorouting", "on");

add_line(modelName, "CellModel/2", "ThermalManager/1", "autorouting", "on");
add_line(modelName, "CellModel/7", "ThermalManager/2", "autorouting", "on");
add_line(modelName, "CellModel/8", "ThermalManager/3", "autorouting", "on");

add_line(modelName, "CellModel/1", "EnergyEstimator/1", "autorouting", "on");
add_line(modelName, "BatterySupervisor/1", "EnergyEstimator/2", "autorouting", "on");
add_line(modelName, "CellModel/4", "EnergyEstimator/3", "autorouting", "on");
add_line(modelName, "CellModel/6", "EnergyEstimator/4", "autorouting", "on");

add_line(modelName, "CellModel/1", "HealthMonitor/1", "autorouting", "on");
add_line(modelName, "BatterySupervisor/1", "HealthMonitor/2", "autorouting", "on");
add_line(modelName, "CellModel/2", "HealthMonitor/3", "autorouting", "on");
add_line(modelName, "BatterySupervisor/7", "HealthMonitor/4", "autorouting", "on");

add_line(modelName, "CellModel/1", "CommEncoder/1", "autorouting", "on");
add_line(modelName, "BatterySupervisor/1", "CommEncoder/2", "autorouting", "on");
add_line(modelName, "CellModel/2", "CommEncoder/3", "autorouting", "on");
add_line(modelName, "CellModel/4", "CommEncoder/4", "autorouting", "on");
add_line(modelName, "HealthMonitor/1", "CommEncoder/5", "autorouting", "on");
add_line(modelName, "BatterySupervisor/9", "CommEncoder/6", "autorouting", "on");

add_line(modelName, "CurrentProfile/1", "SystemScope/1", "autorouting", "on");
add_line(modelName, "DischargeOnly/1", "SystemScope/2", "autorouting", "on");
add_line(modelName, "BatterySupervisor/1", "SystemScope/3", "autorouting", "on");
add_line(modelName, "CellModel/1", "SystemScope/4", "autorouting", "on");
add_line(modelName, "CellModel/2", "SystemScope/5", "autorouting", "on");
add_line(modelName, "CellModel/3", "SystemScope/6", "autorouting", "on");
add_line(modelName, "CellModel/4", "SystemScope/7", "autorouting", "on");
add_line(modelName, "CellModel/5", "SystemScope/8", "autorouting", "on");
add_line(modelName, "CellModel/6", "SystemScope/9", "autorouting", "on");
add_line(modelName, "CellModel/7", "SystemScope/10", "autorouting", "on");
add_line(modelName, "CellModel/8", "SystemScope/11", "autorouting", "on");
add_line(modelName, "BatterySupervisor/2", "SystemScope/12", "autorouting", "on");
add_line(modelName, "BatterySupervisor/6", "SystemScope/13", "autorouting", "on");
add_line(modelName, "BatterySupervisor/7", "SystemScope/14", "autorouting", "on");
add_line(modelName, "BatterySupervisor/8", "SystemScope/15", "autorouting", "on");
add_line(modelName, "BatterySupervisor/9", "SystemScope/16", "autorouting", "on");
add_line(modelName, "ThermalManager/1", "SystemScope/17", "autorouting", "on");
add_line(modelName, "ThermalManager/2", "SystemScope/18", "autorouting", "on");
add_line(modelName, "EnergyEstimator/1", "SystemScope/19", "autorouting", "on");
add_line(modelName, "EnergyEstimator/2", "SystemScope/20", "autorouting", "on");
add_line(modelName, "EnergyEstimator/5", "SystemScope/21", "autorouting", "on");
add_line(modelName, "HealthMonitor/1", "SystemScope/22", "autorouting", "on");
add_line(modelName, "CommEncoder/1", "SystemScope/23", "autorouting", "on");
add_line(modelName, "CommEncoder/6", "SystemScope/24", "autorouting", "on");

save_system(modelName);
fprintf("Created Simulink model: %s.slx\n", modelName);
